#!/bin/sh
set -e

# Stop the service if running
if [ -d /run/systemd/system ]; then
    deb-systemd-invoke stop fc-agent.service || true
fi

# Automatically added by dh_installsystemd/13.29
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'fc-agent.service' >/dev/null || true
fi
# End automatically added section


exit 0
